services:
  redis:
      image: redis:latest
      ports:
        - "6379:6379"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      DB_HOST: postgres
      POSTGRES_PORT: 5432